version: '3.8'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=edgecachex
    ports:
      - "5432:5432"

  gateway:
    build: ./gateway-service
    restart: always
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - WORKER_URL=http://worker:5001
    depends_on:
      - redis
      - rabbitmq

  worker:
    build: ./worker-service
    restart: always
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/edgecachex?schema=public
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
      - db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
      - PORT=5173
    depends_on:
      - gateway
